### ISSUE TITLE
Different image for camera button

### ISSUE THREAD

**Issue by andr3a88** [AlexLittlejohn/ALCameraViewController#102]
Hi, 

I'm trying to change the image of the camera button. For now I've changed `let cameraButton` to `public var cameraButton`, subclass `CameraViewController` and reassign _cameraButton_ with _myCameraButton_. 

Any other way to change the image without change the _ALCameraViewController_ code?

**Comment by AlexLittlejohn** [comment]
Using `CameraGlobals` you can specify a new bundle to use for images. i.e. if you specify main bundle it will look for all its images inside your project instead of its own bundle. So you can just copy the cameraAssets.xcassets, strings and .xib file to your project and then tweak the images as required.
