### ISSUE TITLE
Replace Image Icons

### ISSUE THREAD

**Issue by joebenton** [AlexLittlejohn/ALCameraViewController#127]
I am using your library via cocoapods and wanted to know how I can change the default icons to my own. 

Am I correct in thinking I go into the Resources folder (Pods > ALCameraViewController > Resources) and switch out the images in CameraViewAsses.xcassets with my own?

Or is there a better way to do this?

**Comment by AlexLittlejohn** [comment]
There is a better way.
• First copy the `CameraView.strings` and `CameraViewAssets.xcassets` files to your project
• Before instantiating `CameraViewController` set `CameraGlobals.shared.bundle` property to `NSBundle.mainBundle`
• Replace any icons you want to inside `CameraViewAssets.xcassets`

It's a bit involved but thats the cleanest way to do it otherwise Cocoapods will overwrite your changes.

**Comment by joebenton** [comment]
Thanks @AlexLittlejohn that makes sense. However, I get as far as `CameraGlobal.shared.` but `bundle` does not come up in autocomplete and xcode errors:

`Value of type 'CameraGlobals' has no member 'bundle'`

Im am putting this in `viewDidLoad` just before I instantiate `CameraViewController`

**Comment by AlexLittlejohn** [comment]
It seems the property isn't public at the moment. Will create a fix for it shortly

**Comment by AlexLittlejohn** [comment]
This is fixed in the most recent version

**Comment by joebenton** [comment]
Thanks @AlexLittlejohn. Is this released on cocoapods, `pod update` is still pulling down 1.2.0?
