### ISSUE TITLE
StartSession takes long time

### ISSUE THREAD

**Issue by rocket-enterprise** [AlexLittlejohn/ALCameraViewController#146]
I am using the latest version for Swift 2.x - and ill have a problem with iOS10. When ill start a new Camera Session again, it takes up to 7 Seconds to show the Camera. This is only on iOS10, and works perfectly with iOS9.

When ill try your Swift 3 Build, it still works in iOS10. Ill tried lot of things to deinit or manually close the session, but with no success. When then session should start again, there is a long lag.

Can u tell me how you solved that with your new Swift 3.0 build?

**Comment by rogomantik** [comment]
same for me
the image is shown on average after 9 seconds
Meanwhile, the screen is black but I can take photos properly
inside CameraView
```
        print("\(NSDate()) 1") // 14:56:28 +0000 1
        if session.canAddInput(input) {
            self.session.addInput(self.input)
        }
        print("\(NSDate()) 2") //  14:56:37 +0000 2
```

i changed
```
dispatch_async(dispatch_get_main_queue()) {
            self.createPreview()
        }
```
to
```
        dispatch_async(cameraQueue()) { ////This can even be removed
            self.createPreview()
        } /// because createSession already run on cameraQueue
```
and the NSDate show the same time
I think that needs to use cameraQueue even somewhere else
later I do some other test

**Comment by rocket-enterprise** [comment]
Please let me know if you found something out :)

**Comment by rogomantik** [comment]
I did other tests. I'm using the 1.2.3 release version using an iphone for ios10 and the simulator  for previous versions and xcode 7.3.1

the shot button became active and the camera is ready. the problem seems to be in AVCaptureVideoPreviewLayer or the view sublayer that remains black
if i touch the screen to trigger focus the image is shown instantly
I wasn't able to simulate a touch in the center of the screen
It also appears to stop responding when you open multiple apps that use the camera

Meanwhile I added formsheet support for ipad this way
cameraglobals
 ```
   public var presentationStyle = UIModalPresentationStyle.FormSheet //default

    public func updatePhotoLibraryThumbnailSize (controllerWidth: CGFloat) {
        photoLibraryThumbnailSize = CGSizeMake((controllerWidth - ((columns * itemSpacing) - itemSpacing))/columns, (controllerWidth - ((columns * itemSpacing) - itemSpacing))/columns)
    }
```
cameraviewcontroller
 ```
        let imagePicker = PhotoLibraryViewController()
         let navigationController = UINavigationController(rootViewController: imagePicker)-        
        navigationController.modalPresentationStyle = CameraGlobals.shared.presentationStyle
///////////
public init(croppingEnabled: Bool, allowsLibraryAccess: Bool = true, completion: CameraViewCompletion) {
        super.init(nibName: nil, bundle: nil)
        self.modalPresentationStyle = CameraGlobals.shared.presentationStyle
```
confirmviewcontroller

    super.init(nibName: "ConfirmViewController", bundle: CameraGlobals.shared.bundle)
        self.modalPresentationStyle = CameraGlobals.shared.presentationStyle

libraryviewcontroller
```

    private lazy var collectionView: UICollectionView = {
[...]
        collectionView.alpha = 0
        return collectionView
///////////
    public override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        CameraGlobals.shared.updatePhotoLibraryThumbnailSize(view.bounds.width) //before viewDidAppear view.bounds.width have size fullscreen and collection 0,0
        (collectionView.collectionViewLayout as! UICollectionViewFlowLayout).itemSize = CameraGlobals.shared.photoLibraryThumbnailSize
        collectionView.collectionViewLayout.invalidateLayout()
        UIView.animateWithDuration(0.1) {
            self.collectionView.alpha = 1
        }
    }

```
can be set by 
        CameraGlobals.shared.presentationStyle  = UIModalPresentationStyle.FullScreen // PageSheet  /default is FormSheet
before
let cameraViewController = CameraViewController(cropping.....

I'ts just a mod but can be implemented better
Is there a way to avoid saving image in camera roll and just use in the completition handler?

**Comment by rogomantik** [comment]
Maybe I solved
the problem was I think in competing operations in order
CameraView.swift
```
    public func startSession() {
        dispatch_async(cameraQueue) {
            self.createSession()
//            self.session?.startRunning()
        }
    }
```
private func createPreview() {
```
       preview = AVCaptureVideoPreviewLayer(session: session)
        preview.videoGravity = AVLayerVideoGravityResizeAspectFill
        preview.frame = bounds

        dispatch_async(dispatch_get_main_queue()) {
            self.layer.addSublayer(self.preview)
            self.session.startRunning()
        }        
    }
```

I tested with the camera button and by adding in the storyboard a view: cameraview and 
    @IBOutlet weak var camera: CameraView!

and calling
 ```
override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        camera.startSession()
    }
    override func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)
        camera.stopSession()
    }
```
seems to work. sometimes the view freeze when the app go background/foreground but I think because i dont check the UIApplicationDidBecomeActiveNotification and the others. the CameraViewController seems not affected


I added the saving photos in an album
CameraGlobals
`    public var albumName = "Album Name"`
Singleimagesaver
```
let assetCollection: PHAssetCollection? = {
        var assetCollection: PHAssetCollection? = nil
        
        let fetchOptions = PHFetchOptions()
        fetchOptions.predicate = NSPredicate(format: "title = %@", CameraGlobals.shared.albumName)
        let collection = PHAssetCollection.fetchAssetCollectionsWithType(.Album, subtype: .Any, options: fetchOptions)
        
        if collection.firstObject != nil {
            return collection.firstObject as? PHAssetCollection
        }
        
        do {
        try PHPhotoLibrary.sharedPhotoLibrary().performChangesAndWait({
            PHAssetCollectionChangeRequest.creationRequestForAssetCollectionWithTitle(CameraGlobals.shared.albumName)
        })
        }catch{ return nil
            
        }
        assetCollection = PHAssetCollection.fetchAssetCollectionsWithType(.Album, subtype: .Any, options: fetchOptions).firstObject as? PHAssetCollection
       
        return assetCollection
    }()
```
```
private func _save() {
        guard let image = image else {
            self.invokeFailure()
            return
        }
        var assetIdentifier: PHObjectPlaceholder?
        
        if assetCollection == nil {
            self.invokeFailure()
            return
        }
        
        PHPhotoLibrary.sharedPhotoLibrary().performChanges({
            let assetChangeRequest = PHAssetChangeRequest.creationRequestForAssetFromImage(image)
            assetIdentifier = assetChangeRequest.placeholderForCreatedAsset
            let albumChangeRequest = PHAssetCollectionChangeRequest(forAssetCollection: self.assetCollection!)
            albumChangeRequest?.addAssets([assetIdentifier!])
        }) { finished, error in
                
                guard let assetIdentifier = assetIdentifier where finished else {
                    self.invokeFailure()
                    return
                }
                
                self.fetch(assetIdentifier)
        }
    }
```
It seems to work. the name must be changed by setting
CameraGlobals.shared.albumName = "New album name"
before call
CameraViewController(croppingEnabled: croppingEnabled, allowsLibraryAccess: libraryEnabled)
the album is created if not exist

The solution to the main issue seems to work as well as the proposed changes but I'm waiting for confirmation

Cheers :)

**Comment by AlexLittlejohn** [comment]
The solution is to use the new AVPhotoCapture API's available in iOS 10 instead.
I am already working on this.

**Comment by AlexLittlejohn** [comment]
Have a look at v1.2.6 to see if the problem persists

**Comment by rogomantik** [comment]
Works
