### ISSUE TITLE
Frontal camera cropping area bug

### ISSUE THREAD

**Issue by npu3pak** [AlexLittlejohn/ALCameraViewController#221]
1. Let's take a photo with frontal camera
![img_0017](https://user-images.githubusercontent.com/842285/30364812-73dda6a4-986e-11e7-90a4-d3ba07221bcc.PNG)

2. Adjust cropping area like this
![img_0018](https://user-images.githubusercontent.com/842285/30364829-80b5543a-986e-11e7-9e16-b4e9ab4496f4.PNG)

3. And let's see what we have
![img_0019](https://user-images.githubusercontent.com/842285/30364840-8771cdee-986e-11e7-83e4-2e9bd5b04109.PNG)

I can't reproduce the bug with rear camera or gallery

**Comment by ajacquelin** [comment]
I have the same issue on front camera with an iPhone 6 on iOS 11.

**Comment by npu3pak** [comment]
In my case it was iOS 10 and iPhone SE

**Comment by mkelitz** [comment]
Same issue here with ios11 and iPhone 7 (only with front camera; rear camera works just fine)

**Comment by newdev7** [comment]
Hi,
I'm also facing the same issue. I'm testing this in iPhone5c.
I tried to do some changes in crop() function.

Before passing the `rect.applying(rectTransform)` in `cgImage?.cropping(to:)`, I'm checking the size of both UIImage and its CGImage. For UIImage, the size returned as 960x1280 but for its CGImage, it returned 1280x960.

If the height of UIImage and its CGImage is different, I'm interchanging the x and y co-ordinates of the `rect` and passing it into the `cgImage?.cropping(to:)`.

Now for front camera, there is no issues. But the same issue occurred for rear camera.

To fix this, I removed the `rectTransform` transform and used default transform, `rectTransform = CGAffineTransform.identity`, for all orientation. Now, it returned the correct cropped image for both front and rear camera. But it is returning the correct cropped image only for the default crop frame. I tried to change the crop frame and tested. It returned the wrong image.

Before this, I tried to remove flipping image of the preview in the function `takePhoto()` in CameraShot.swift file. At that time there was no issues with both from camera and rear camera but the image was not flipped for front camera since I removed that code.

I'm planning to interchange the co-ordinates for front camera and use the same co-ordinates for rear camera in the `rect`. Shall I use it like this or will it create any issues in other places?

**Comment by npu3pak** [comment]
I faced with this bug again on 3.0.2 demo app.
![img_0031](https://user-images.githubusercontent.com/842285/38027013-f185a530-3296-11e8-8dfe-9ba5aac46d08.png)
![img_0032](https://user-images.githubusercontent.com/842285/38027015-f3cd56e4-3296-11e8-8874-eb6e6d56b97c.png)

**Comment by kublaios** [comment]
+1, the issue remains.

**Comment by lightman73** [comment]
+1. 

The issue persists. Tried both the latest version, and the fork by [https://github.com/kkieffer](https://github.com/kkieffer) .
