### ISSUE TITLE
Camera ignores dismiss call and example code doesn't work with latest pod version.

### ISSUE THREAD

**Issue by defal7** [AlexLittlejohn/ALCameraViewController#24]
func photoButtonTapped(sender: UIButton) {
 
        let cameraViewController = ALCameraViewController(croppingEnabled: false) { image in
       
            self.imageView.image = image
            self.dismissViewControllerAnimated(true, completion: nil)
            
            // Do something with your image here.
            // If cropping is enabled this image will be the cropped version
        }        
        presentViewController(cameraViewController, animated: true, completion: nil)
    }
    

This code above will make the camera appear, but the dismiss method is ignored. Any ideas why?

**Comment by burgesschentz** [comment]
I had the same issue

**Comment by LunarFlash** [comment]
same issue for me also.

**Comment by sbdk** [comment]
encounter the same issue. Find where the problem is and hope it works for other people who find this thread.

**My code before problem fixed:**
<img width="554" alt="screen shot 2017-02-23 at 12 01 00 am" src="https://cloud.githubusercontent.com/assets/13881914/23249856/42da97fe-f95b-11e6-89cd-108dee1c83b3.png">

the problem is the completion handler of CameraViewController check image & asset value for deciding whether it should dismiss itself or not. If any one of these two is nil, the dismiss button will work.  Source code:
<img width="453" alt="screen shot 2017-02-22 at 11 54 36 pm" src="https://cloud.githubusercontent.com/assets/13881914/23249689/7cf6cb02-f95a-11e6-9d58-afc7058024a2.png">

But in my code, the dismiss function never got the change to check these two values since I returned the function too early.

**Easy fix:  add an extra dismiss function into guard closure.**
<img width="555" alt="screen shot 2017-02-22 at 11 59 39 pm" src="https://cloud.githubusercontent.com/assets/13881914/23249809/05db8a66-f95b-11e6-9540-1252971bdc37.png">
