### ISSUE TITLE
front camera multiple issues

### ISSUE THREAD

**Issue by stachon** [AlexLittlejohn/ALCameraViewController#58]
Hi, just tested Front camera capture, run into few issues:

1) Cropping is wrong. I think the Mirrored cases in #41 need to be handled separately
2) The built-in camera app on iPhone removes the mirroring after the photo is taken. Preview is mirrored so you can take a selfie like in mirror, but taken photo is not mirrored so that for example text is readable.
3) When taking a selfie with front camera in Portrait orientation, the image saved to Library is flipped upside down.

**Comment by AlexLittlejohn** [comment]
1. This seems to be related to issue number 3
2. I went this route because it's weird to see the photo flip itself around after taking it and users were reporting it as a bug. As a side note Whatsapp also takes this approach to selfies taken on the front camera.
3. Yes this is an issue definitely, however fetching these photos from the library and showing them in cropper/confirm view displays the photos correctly again which is just strange.

**Comment by AlexLittlejohn** [comment]
In v2.0 I want to remove the confirm step and use an approach that more closely resembles the built-in app with a miniature image shown on the bottom left of the camera view. This will allow me to remove the flipping of images for the crop step as it will not be shown directly after taking a photo.

**Comment by AlexLittlejohn** [comment]
I have fixed this, however images are now flipped when going from camera -> crop view. I will investigate a more complete solution at some point.
A new hotfix release has been made v1.1.7

**Comment by stachon** [comment]
Thanks for quick fix!
